wandb_version: 1

params_path:
  desc: null
  value: ../config/config_baseline.txt
model_params_path:
  desc: null
  value: ../models/minkloc3dv2.txt
debug:
  desc: null
  value: false
dataset_folder:
  desc: null
  value: /home/datutuda/PycharmProjects/SLAM/dataset/benchmark_datasets
save_freq:
  desc: null
  value: 0
num_workers:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 2048
batch_split_size:
  desc: null
  value: 128
batch_expansion_th:
  desc: null
  value: null
batch_size_limit:
  desc: null
  value: 2048
batch_expansion_rate:
  desc: null
  value: null
val_batch_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 400
optimizer:
  desc: null
  value: Adam
scheduler:
  desc: null
  value: MultiStepLR
scheduler_milestones:
  desc: null
  value:
  - 250
  - 350
weight_decay:
  desc: null
  value: 0.0001
loss:
  desc: null
  value: truncatedsmoothap
positives_per_query:
  desc: null
  value: 4
tau1:
  desc: null
  value: 0.01
margin:
  desc: null
  value: null
similarity:
  desc: null
  value: euclidean
aug_mode:
  desc: null
  value: 1
set_aug_mode:
  desc: null
  value: 1
train_file:
  desc: null
  value: training_queries_baseline2.pickle
val_file:
  desc: null
  value: test_queries_baseline2.pickle
test_file:
  desc: null
  value: null
model_params.model_params_path:
  desc: null
  value: ../models/minkloc3dv2.txt
model_params.model:
  desc: null
  value: MinkLoc
model_params.output_dim:
  desc: null
  value: 256
model_params.coordinates:
  desc: null
  value: cartesian
model_params.quantization_step:
  desc: null
  value: 0.01
model_params.quantizer:
  desc: null
  value: <datasets.quantization.CartesianQuantizer object at 0x7f9652217b80>
model_params.normalize_embeddings:
  desc: null
  value: false
model_params.feature_size:
  desc: null
  value: 256
model_params.planes:
  desc: null
  value:
  - 64
  - 128
  - 64
  - 32
model_params.layers:
  desc: null
  value:
  - 1
  - 1
  - 1
  - 1
model_params.num_top_down:
  desc: null
  value: 2
model_params.conv0_kernel_size:
  desc: null
  value: 5
model_params.block:
  desc: null
  value: ECABasicBlock
model_params.pooling:
  desc: null
  value: GeM
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694271062.228396
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.17
      5: 0.15.9
      8:
      - 5
